team_names = [
    'Arsenal',
    'Aston Villa',
    'Bournemouth',
    'Burnley',
    'Chelsea',
    'Crystal Palace',
    'Everton',
    'Leicester City',
    'Liverpool',
    'Manchester City',
    'Manchester United',
    'Newcastle United',
    'Sheffield United',
    'Southampton',
    'Tottenham Hotspur',
    'West Ham United',
]

player_names = [
    'Pierre-Emerick Aubameyang',
    'Jack Grealish',
    'Callum Wilson',
    'Chris Wood',
    'Tammy Abraham',
    'Christian Pulisic',
    'Richarlison',
    'Jamie Vardy',
    'Mohamed Salah',
    'Raheem Sterling',
    'Marcus Rashford',
    'Allan Saint-Maximin',
    'John Lundstram',
    'Danny Ings',
    'Harry Kane',
    'Michail Antonio',
    'David Luiz',
    'Tyrone Mings',
    'Nathan Ake',
    'Ben Mee',
    'Kurt Zouma',
    'Gary Cahill',
    'Michael Keane',
    'Caglar Soyuncu',
    'Virgil van Dijk',
    'Aymeric Laporte',
    'Harry Maguire',
    'Federico Fernandez',
    'John Egan',
    'Jack O\'Connell',
    'Jan Bednarek',
    'James Ward-Prowse',
    'Harry Winks',
    'Declan Rice',
    'Granit Xhaka',
    'Douglas Luiz',
    'Mateo Kovacic',
    'Luka Milivojevic',
    'Andre Gomes',
    'Wilfred Ndidi',
    'Rodri',
    'Fred',
    'Jonjo Shelvey',
    'John Fleck',
    'Oriol Romeu',
    'Tangu Ndombele',
    'Mark Noble',
    'Kevin De Bruyne',
    'David Silva',
    'Bruno Fernandes',
    'Allan Saint-Maximin',
    'James Maddison',
    'Jordan Henderson',
    'James Ward-Prowse',
    'Mason Mount',
    'Wilfred Ndidi',
    'Declan Rice',
    'Mateo Kovacic',
    'Jonjo Shelvey',
    'John Fleck',
    'Jack Grealish',
    'David Silva',
    'Bruno Fernandes',
    'Raheem Sterling',
]

captain_names = [
    'Pxierre-Emerick Aubameyang',
    'Jxack Grealish',
    'Cxallum Wilson',
    'Cxhris Wood',
    'Txammy Abraham',
    'Cxhristian Pulisic',
    'Rxicharlison',
    'Jxamie Vardy',
    'Mxohamed Salah',
    'Rxaheem Sterling',
    'Mxarcus Rashford',
    'Axllan Saint-Maximin',
    'Jxohn Lundstram',
    'Dxanny Ings',
    'Hxarry Kane',
    'Mxichail Antonio',
]
