# Generated by Django 4.0.10 on 2024-10-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplayer',
            name='is_captain',
            field=models.BooleanField(default=False),
        ),
    ]
