# Generated by Django 4.0.10 on 2024-10-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplayer',
            name='racks_lost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teamplayer',
            name='racks_won',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
