# Generated by Django 4.0.10 on 2024-09-24 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamplayer',
            unique_together={('team_season', 'player')},
        ),
    ]
