# Generated by Django 4.0.10 on 2024-09-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='handicap_type',
            field=models.CharField(choices=[('integer', 'Integer'), ('letter', 'Letter'), ('custom', 'Custom')], default='integer', max_length=20),
        ),
    ]
