# Generated by Django 4.0.10 on 2024-09-24 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_teamplayer_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamseason',
            unique_together={('team', 'season')},
        ),
    ]
