# Generated by Django 4.0.10 on 2024-10-26 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_teamseason_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamseason',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamseason', to='core.season'),
        ),
    ]
