# Generated by Django 4.0.10 on 2024-09-22 20:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_league_handicap_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='handicap_type',
        ),
        migrations.AddField(
            model_name='league',
            name='handicap_range',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], size=None),
        ),
    ]
