# Generated by Django 4.0.10 on 2024-09-22 20:28

import core.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_league_handicap_type_league_handicap_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='handicap_range',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=core.models.default_handicap_range, size=None),
        ),
    ]
