# Generated by Django 4.0.10 on 2024-10-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_schedule_matchnight_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='default_start_time',
            field=models.TimeField(default='19:00'),
        ),
        migrations.AlterField(
            model_name='matchnight',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
