# Generated by Django 4.0.10 on 2024-10-03 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_schedule_default_start_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchnight',
            unique_together={('date', 'schedule')},
        ),
    ]
