# Generated by Django 4.0.10 on 2024-09-20 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_team_captain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='player_id',
            new_name='player_profile',
        ),
    ]
