# Generated by Django 4.0.10 on 2024-10-03 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_matchnight_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='team_b',
            new_name='away_team',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='team_a',
            new_name='home_team',
        ),
    ]
