# Generated by Django 4.0.10 on 2024-10-03 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_team_b_match_away_team_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('match_night', 'home_team', 'away_team')},
        ),
    ]
