# Generated by Django 4.0.10 on 2024-10-04 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_match_result_match_away_race_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_race_to', models.IntegerField(blank=True, null=True)),
                ('away_race_to', models.IntegerField(blank=True, null=True)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('winner', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(default='Scheduled', max_length=50)),
                ('player_snapshot', models.JSONField(blank=True, null=True)),
                ('away_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='core.teamplayer')),
                ('home_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='core.teamplayer')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='core.match')),
            ],
        ),
    ]
