name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
      - name: Build and start services
        run: docker-compose up -d --build
      - name: Wait for DB to be ready
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db"
      - name: Run Tests
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Run Lint
        run: docker-compose run --rm app sh -c "flake8"
      - name: Display Logs
        if: failure()
        run: docker-compose logs
      - name: Tear down services
        if: always()
        run: docker-compose down
